name: Nightly Build

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 5 AM
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Prevent Shallow Clone to satisfy Sonarqube
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run Maven verify with nightly profile
        run: mvn verify -Pnightly

      - name: Archive CycloneDX BOM
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cyclonedx-bom
          path: target/bom.xml  # Adjust this path if the output location is different